# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=<db_user>
      - MARIADB_DATABASE=<db_name>
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - "6382:6379"
    environment:
      - name=value
  composer-aux:
    image: composer
    volumes:
      - '.:/app'
    command: install --ignore-platform-reqs --no-scripts

  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=<host>
      - DB_PORT=3306
      - DB_USERNAME=<db_name>
      - DB_DATABASE=<db_database>
      - DB_PASSWORD=<db_pass>
      - CACHE_DRIVER=redis
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    volumes:
      - '.:/app'
    depends_on:
      - composer-aux
      - mariadb
      - redis  